server:
  port: ${sp.sysmanagement}
spring:
  application:
    name: ${sn.sysmanagement}
seata:
  tx-service-group: tx-business
  enabled: true
  service:
    # seata服务器地址
    grouplist:
      default: ${seata.default}
    # 虚拟组和分组映射：key的名字和tx-service-group一致
    vgroup-mapping:
      tx-business: default
    # 开启全局事务
    disable-global-transaction: false
