server:
  port: ${sp.mycenter}
spring:
  application:
    name: ${sn.mycenter}
    #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.130:3307/ktgmes
    username: root
    password: 123
  profiles:
    active: test # 激活test配置文件
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.addr} # Nacos服务发现地址
        #namespace: ${nacos.namespace} # Nacos命名空间
